// 스터디룸 섹션 애니메이션 관련 상수
const IMAGE_SIZE_MOBILE = 200;
const IMAGE_SIZE_TABLET = 300;
const IMAGE_GAP = 32;
const BUTTON_WIDTH = 32;
const TITLE_ROW_GAP = 8;
const ANIMATION_DURATION = 400;
const TABLET_BREAKPOINT = 768;

export const STUDYROOM_SECTION_CONSTANTS = {
  IMAGE_SIZE_MOBILE,
  IMAGE_SIZE_TABLET,
  IMAGE_GAP,
  BUTTON_WIDTH,
  TITLE_ROW_GAP,
  ANIMATION_DURATION,
  TABLET_BREAKPOINT,
} as const;
